name: 'Installing Yarn dependencies'
description: 'Installs the dependencies using Yarn'

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
      with:
        path: |
          ./node_modules/
        # If just `WORKSPACE` or `yarn.lock` is changed, the most recent cache can be restored.
        # See: https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action.
        key: v1-angular-main-deps-${{hashFiles('WORKSPACE')}}-${{hashFiles('yarn.lock')}}
        restore-keys: v1-angular-main-deps-

    - run: yarn install --frozen-lockfile --non-interactive
      shell: bash
